baseURL = "https://icodesign.me/"
title = "icodesign"
theme = "simple"
disableKinds = ["taxonomy", "taxonomyTerm"]
author = "icodesign"
disqusShortname = "icodesign"
googleAnalytics = "UA-38012898-4"

#高亮markdown的代码块
pygmentsCodefences = true 
#高亮markdown中没有标注语言的代码块
pygmentsCodefencesGuessSyntax = true 
#高亮主题
pygmentsStyle = 'xcode'

[params]
  Logo = "images/logo.svg"
  MenuPath = "/menu"
  images = ["/images/site_image.jpeg"]

[languages]
  [languages.en]
    title = "icodesign"
    subtitle = "Blogging about technology, programming, my works and life"
    keywords = "technology, programming, swift, ios, fullstack"

  [languages.cn]
    title = "罐言罐语 icodesign"
    subtitle = "记录科技、编程、我的一些作品以及生活"
    keywords = "科技, 编程, swift, ios, 全栈"

[markup.goldmark.renderer]
# By default, Goldmark does not render raw HTMLs and potentially dangerous links. 
# If you have lots of inline HTML and/or JavaScript, you may need to turn this on.
unsafe= true