baseURL = "https://icodesign.me/"
title = "icodesign"
theme = "simple"
disableKinds = ["taxonomy", "taxonomyTerm"]
author = "icodesign"
disqusShortname = "icodesign"

[params]
  Logo = "images/logo.svg"
  MenuPath = "/menu"
  images = ["/images/site_image.jpeg"]

[languages]
  [languages.en]
    title = "icodesign"
    subtitle = "Blogging about technology, programming, my works and life"
    keywords = "technology, programming, swift, ios, fullstack"

  [languages.cn]
    title = "罐言罐语 icodesign"
    subtitle = "记录科技、编程、我的一些作品以及生活"
    keywords = "科技, 编程, swift, ios, 全栈"
