baseURL = "https://icodesign.me/"
title = "icodesign"
theme = "simple"
disableKinds = ["taxonomy", "taxonomyTerm"]
author = "icodesign"
disqusShortname = "icodesign"
pygmentsCodefences = true #高亮markdown的代码块
pygmentsCodefencesGuessSyntax = true #高亮markdown中没有标注语言的代码块
pygmentsStyle = 'xcode' #高亮主题
googleAnalytics = "UA-38012898-4"

[params]
  Logo = "images/logo.svg"
  MenuPath = "/menu"
  images = ["/images/site_image.jpeg"]

[languages]
  [languages.en]
    title = "icodesign"
    subtitle = "Blogging about technology, programming, my works and life"
    keywords = "technology, programming, swift, ios, fullstack"

  [languages.cn]
    title = "罐言罐语 icodesign"
    subtitle = "记录科技、编程、我的一些作品以及生活"
    keywords = "科技, 编程, swift, ios, 全栈"
